
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not run on branches
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\uk-controller-plugin

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 1                      # clone entire repository history if not defined

environment:
  BOOST_ROOT: C:\Libraries\boost_1_70_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_70_0\stage\lib
  OPENSSL_ROOT: C:\OpenSSL-v111-Win32\include
  OPENSSL_LIBRARYDIR: C:\OpenSSL-v111-Win32\lib\VC\static
  matrix:
    - compiler: msvc-16-seh
      generator: "Visual Studio 2019 Preview"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
      enabled_on_pr: yes

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

install:
  - pip install cpplint
  - ps: .\ci\install-boost.ps1

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true                  # enable MSBuild parallel builds
  project: msvc/UKControllerPlugin.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

# to run your custom scripts instead of automatic tests
test_script:
  - ps: .\ci\run-tests.ps1
  - ps: .\ci\run-lint.ps1
